//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SampleMigrateApp.Models
{
    public class Color
    {
        public Color()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        public int ColorId { get; set; }
        public string Color1 { get; set; } = string.Empty;
        public virtual ICollection<Product> Products { get; set; }
    }
}
